name: Java CI with Maven and MongoDB

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 2 * * 1-5"

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0     # Specify MongoDB version
        ports:
          - 27017:27017
        # options: >-            # Use options to ensure MongoDB is ready
        #   --health-cmd mongo
        #   --health-interval 10s
        #   --health-timeout 5s
        #   --health-retries 5

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      env:
        SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/text-analyzer-db   # MongoDB connection string for your tests
      run: mvn test

